# Generated by Django 5.2.8 on 2025-11-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogType',
            fields=[
                ('id', models.SmallIntegerField(default=models.Value("nextval('log_type_id_seq'::regclass)"), primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'log_type',
            },
        ),
        migrations.AddField(
            model_name='userquerylog',
            name='params',
            field=models.TextField(default=None),
        ),
    ]
